[package]
name = "notfenv/attribute"
description = "Attribute helper class"
version = "1.0.1"
license = "MIT"
authors = ["Mia Fenneki"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@^1"
