[package]
name = "notfenv/attribute"
description = "Attribute helper class"
version = "1.0.0"
license = "MIT"
authors = ["Mia Fenneki"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@^1"
Trove = "sleitnick/trove@^0.5"
Symbol = "sleitnick/symbol@^2"
