title = "Roblox Utility"
gitRepoUrl = "https://github.com/notfenv/Roblox-Utility"
gitSourceBranch = "main"

[home]
includeReadme = true
enabled = true

[docusaurus]
tagline = "Utility modules for Roblox"
organizationName = "Mia Vince"
projectName = "Roblox Utility"
url = "https://notfenv.github.io"
