[package]
name = "notfenv/regionalutils"
description = "Geolocation utilities"
version = "1.0.0"
license = "MIT"
authors = ["Mia Vince"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
