[package]
name = "notfenv/robloxpolicy"
description = "Policy handler"
version = "1.0.0"
license = "MIT"
authors = ["Mia Vince"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
t = "osyrisrblx/t@^3.0.0"
Promise = "evaera/promise@^4"
